- hosts: all
  connection: local
  gather_facts: no

  vars:
    - instance_types:
        - c1.medium
        - c1.xlarge
        - c3.2xlarge
        - c3.4xlarge
        - c3.8xlarge
        - c3.large
        - c3.xlarge
        - m1.large
        - m1.medium
        - m1.small
        - t1.micro

  tasks:
    - local_action: 
        module: ec2
        keypair: grw
        image: ami-ad184ac4
        instance_type: $item
        region: us-east-1
        wait: true
      register: ec2
      with_items: $instance_types

    - name: Add new instance to host group
      local_action: add_host hostname={{ item.instances.0.public_ip }} instance_type={{ item.instances.0.instance_type }} groupname=launched
      with_items: ec2.results

    - name: Wait for instances to come up
      local_action: wait_for host={{ item.instances.0.public_dns_name }} port=22
      with_items: ec2.results

- hosts: launched
  gather_facts: no
  user: ubuntu

  vars:
   - minerd_url: https://raw.github.com/georgewhewell/aws-bench/master/minerd
   - script_url: https://raw.github.com/georgewhewell/aws-bench/master/benchmark.py
   - mine_cmd: ~/minerd -o stratum+tcp://stratum01.hashco.ws:8888 -u balindwalin.1 -p x

  tasks:
   # little money wow
   - shell: echo "shutdown -P now" | sudo at now + 50 minutes
     sudo: yes

   # download minerd
   - get_url: url={{ minerd_url }} dest=~/minerd mode=0777

   # run benchmark
   - shell: wget -qO- {{ script_url }} | python
     register: hashrate

   # Mine for a while until we lose the machine :)
   - shell: nohup {{ mine_cmd }} > /dev/null 2>&1 &

   # save results
   - local_action: 
        module: shell echo {{ instance_type }},{{ hashrate.stdout }} >> log.txt
